In [1]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 578.0 MB 16 kB/s 
     |████████████████████████████████| 1.7 MB 54.8 MB/s 
     |████████████████████████████████| 438 kB 54.5 MB/s 
     |████████████████████████████████| 5.9 MB 61.9 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: keras
    Found existing installation: keras 2.8.0
    Uninstalling keras-2.8.0:
      Successfully uninstalled keras-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Successfully uninstalled gast-0.5

In [2]:
import tensorflow as tf
print(tf.__version__)

2.10.0


In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [14]:
### sentences
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'I would like to travel']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'I would like to travel']

In [10]:
# Vocabulary size
voc_size=500

In [15]:
one_hot_resp=[one_hot(words,voc_size) for words in sent]
one_hot_resp

[[277, 40, 215, 281],
 [277, 40, 215, 492],
 [277, 299, 215, 389],
 [94, 22, 219, 499, 418],
 [94, 22, 219, 499, 497],
 [18, 277, 305, 215, 495],
 [94, 376, 308, 190, 35]]

In [16]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [22]:
sent_length=8
embedded_docs = pad_sequences(one_hot_resp,padding='pre',maxlen=sent_length) # padding = 'pre'/'post'
embedded_docs

array([[  0,   0,   0,   0, 277,  40, 215, 281],
       [  0,   0,   0,   0, 277,  40, 215, 492],
       [  0,   0,   0,   0, 277, 299, 215, 389],
       [  0,   0,   0,  94,  22, 219, 499, 418],
       [  0,   0,   0,  94,  22, 219, 499, 497],
       [  0,   0,   0,  18, 277, 305, 215, 495],
       [  0,   0,   0,  94, 376, 308, 190,  35]], dtype=int32)

In [20]:
dim=10 # feature dimension 
model= Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [21]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [23]:
embedded_docs[0]

array([  0,   0,   0,   0, 277,  40, 215, 281], dtype=int32)

In [25]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 34ms/step


array([[[ 7.02456385e-03,  4.77256067e-02,  7.34658167e-03,
         -4.54118252e-02, -4.99412902e-02,  1.03385672e-02,
         -3.67472768e-02,  3.95490043e-02,  1.67052262e-02,
         -2.16165781e-02],
        [ 7.02456385e-03,  4.77256067e-02,  7.34658167e-03,
         -4.54118252e-02, -4.99412902e-02,  1.03385672e-02,
         -3.67472768e-02,  3.95490043e-02,  1.67052262e-02,
         -2.16165781e-02],
        [ 7.02456385e-03,  4.77256067e-02,  7.34658167e-03,
         -4.54118252e-02, -4.99412902e-02,  1.03385672e-02,
         -3.67472768e-02,  3.95490043e-02,  1.67052262e-02,
         -2.16165781e-02],
        [ 7.02456385e-03,  4.77256067e-02,  7.34658167e-03,
         -4.54118252e-02, -4.99412902e-02,  1.03385672e-02,
         -3.67472768e-02,  3.95490043e-02,  1.67052262e-02,
         -2.16165781e-02],
        [ 2.25448646e-02, -2.50862837e-02, -1.99129581e-02,
         -1.53849125e-02,  3.81181724e-02,  6.17337227e-03,
          4.99630012e-02,  4.67167534e-02,  4.439938